image: Visual Studio 2019
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
configuration:
  - Debug
before_build:
  - cmd: nuget install NUnit.Console -Version 3.11.1 -OutputDirectory tools
  - cmd: nuget install OpenCover -Version 4.6.519 -OutputDirectory tools
  - cmd: nuget restore -verbosity quiet
  - cmd: choco install codecov
build:
  project: CDP4-Server.sln
test:
  assemblies:
    only:
      - '**\*.Tests.dll'
  categories:
    except:
      - AppVeyorExclusion
after_test:
  - .\tools\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:".\tools\NUnit.ConsoleRunner.3.11.1\tools\nunit3-console.exe" -targetargs:".\CDP4Orm.Tests\bin\Debug\net452\CDP4Orm.Tests.dll .\CDP4WebServices.API.Tests\bin\Debug\net452\CDP4WebServices.API.Tests.dll" -output:"coverage.xml"
  - codecov -f "coverage.xml" -t e4567a09-8a81-4da7-b003-57c8d7d41dbb
